spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
    exchange: bip.exchange
    queue: bip.queue
    routingkey: bip.routingkey

server:
  error:
    include-stacktrace: never